artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/ABIGAILDEBBY/End-to-end-Machine-Learning-Project-with-mlflow/raw/main/winequality-data.zip
  local_data_file: artifacts/data_ingestion/data.zp
  unzip_dir: artifacts/data_ingestion
